### ISSUE TITLE
More than one TCS230 on the same arduino

### ISSUE THREAD

**Issue by carlos-adir** [MajicDesigns/MD_TCS230#4]
I am trying to use more than one TCS230 color sensor at the same arduino.
I have already read the [Library documentation](https://majicdesigns.github.io/MD_TCS230/) mentioned on the README file. But I didn't find anything about which input pins and how should I declare my sensors in the code.
The only thing mentioned there is that I should use the pin 5 on arduino Uno.

**Comment by MajicDesigns** [comment]
You will need to make sure the OE (Output Enable) pin is set to not output from the sensors you are not using. Then they can all share the same pin 5 on the Arduino. Info on the OE pin is in the datasheet for the device.

**Comment by MajicDesigns** [comment]
Closed due to lack of comms from OP
